#include "Chapter01_Bird\2.1hello_triangle\HelloTriangleDockWidget.h"
#include "Chapter01_Bird\3.1shaders_interpolation\ShadersDockWidget.h"
#include "Chapter01_Bird\4.1texture\TextureDockWidget.h"
#include "Chapter01_Bird\5.1transformations\TransformationsDockwidget.h"
#include "Chapter01_Bird\6.1coordinate_systems\CoordinateSystemsDockWidget.h"
#include "Chapter01_Bird\7.1camera\\CameraDockWidget.h"
#include "Chapter01_Bird\8.1review\ReviewDockWidget.h"
#include "Chapter02_Lighting\2.1_basic_lighting\BasicLighting_DockWidget.h"
#include "Chapter02_Lighting\3.1_materials\Materials_DockWidget.h"
#include "Chapter02_Lighting\4.1_lighting_maps\LightingMaps_DockWidget.h"
#include "Chapter02_Lighting\5.1_light_casters\LightCasters_DockWidget.h"
#include "Chapter02_Lighting\6.1_multiple_lights\MultiLights_DockWidget.h"
#include "Chapter02_Lighting\7.1_review\ReviewLighting_DockWidget.h"
#include "Chapter03_Model\1.1_load_model\LoadModel_DockWidget.h"
#include "Chapter04_AdvancedOpenGL\AdvancedOpenGL_DockWidget.h"
#include "Chapter05_AdvancedLighting\AdvancedLighting_DockWidget.h"

// #include "Chapter01_Bird\2.1hello_triangle\HelloTriangle.h"
// #include "Chapter01_Bird\2.1hello_triangle\HelloTriangleIndexed.h"
// #include "Chapter01_Bird\2.1hello_triangle\HelloTriangleExercise1.h"
// #include "Chapter01_Bird\2.1hello_triangle\HelloTriangleExercise2.h"
// #include "Chapter01_Bird\2.1hello_triangle\HelloTriangleExercise3.h"
// #include "Chapter01_Bird\3.1shaders_interpolation\ShadersInterpolation.h"
// #include "Chapter01_Bird\4.1texture\Textures.h"
// #include "Chapter01_Bird\4.1texture\TextureWidget.h"
// #include "Chapter01_Bird\4.1texture\TexturesExercise2.h"
// #include "Chapter01_Bird\4.1texture\TexturesExercise3.h"
// #include "Chapter01_Bird\4.1texture\TexturesExercise4.h"
// #include "Chapter01_Bird\5.1transformations\Transformations.h"
// #include "Chapter01_Bird\6.1coordinate_systems\CoordinateSystems.h"
// #include "Chapter01_Bird\6.1coordinate_systems\CoordinateSystemsDepth.h"
// #include "Chapter01_Bird\6.1coordinate_systems\CoordinateSystemsExercise.h"
// #include "Chapter01_Bird\7.1camera\CameraCircle.h"
// #include "Chapter01_Bird\7.1camera\CameraInteract.h"
// #include "Chapter01_Bird\7.1camera\CameraClass.h"
